destination: "public/datasync"
exclude: [Gemfile, Gemfile.lock, .rvmrc, public]
incremental: true

# TODO: Get a unique tracking code for datasync
ga_tracking_code: "UA-9046230-3"

subsite: dev
title: Socrata DataSync
root: "/datasync"
baseurl: "/datasync"
icon: fa fa-refresh
github_repo: https://github.com/socrata/datasync
contribute: /datasync/contributing.html
gems:
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-mentions
- jekyll-feed
